version: '3.8'

services:
  auth:
    build: ./auth
    volumes:
      - ./auth:/app
    working_dir: /app
    ports:
      - "5000:5000"
    env_file:
      - ./auth/.env.dev
    depends_on:
      - sql

  products:
    build: ./products
    volumes:
      - ./products:/app
    working_dir: /app
    ports:
      - "5002:5000"
    env_file:
      - ./products/.env.dev
    depends_on:
      - mongo

  web:
    build: ./web
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3000:5173"
    
  sql:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: stock_db
    volumes: 
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
  node_modules: