version: '3.8'

services:
  auth:
    build: ./auth
    volumes:
      - ./auth:/app
    working_dir: /app
    ports:
      - "5000:5000"
    env_file:
      - ./auth/.env
    depends_on:
      - sql
  
  users:
    build: ./users
    volumes:
      - ./users:/app
    working_dir: /app
    ports:
      - "5001:5000"
    env_file:
      - ./users/.env
    depends_on:
      - sql

  orders:
    build: ./orders
    volumes:
      - ./orders:/app
    working_dir: /app
    ports:
      - "5002:5000"
    env_file:
      - ./orders/.env
    depends_on:
      - sql
  
  products:
    build: ./products
    volumes:
      - ./products:/app
    working_dir: /app
    ports:
      - "5003:5000"
    env_file:
      - ./products/.env
    depends_on:
      - mongo
  
  email:
    build: ./email
    volumes:
      - ./email:/app
      - email_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "5004:5000"
    env_file:
      - ./email/.env

  carrito:
    build: ./carrito/flaskapp
    volumes:
      - ./carrito/flaskapp:/app
    working_dir: /app
    ports:
      - "5005:5000"
    depends_on:
      - redis

  web:
    build: ./web
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3000:5173"
  
  redis:
    build: ./carrito/redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  sql:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: stock_db
    volumes: 
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
  web_node_modules:
  email_node_modules:
  redis:
    driver: local